// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PoolApi.Data;

namespace PoolApi.Migrations
{
    [DbContext(typeof(PoolContext))]
    [Migration("20200309204221_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0");

            modelBuilder.Entity("PoolApi.Pool", b =>
                {
                    b.Property<int>("poll_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("poll_description")
                        .HasColumnType("TEXT");

                    b.HasKey("poll_id");

                    b.ToTable("Values");
                });
#pragma warning restore 612, 618
        }
    }
}
