// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PoolApi.Data;

namespace PoolApi.Migrations
{
    [DbContext(typeof(PoolContext))]
    partial class PoolContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0");

            modelBuilder.Entity("PoolApi.Option", b =>
                {
                    b.Property<int>("option_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("option_description")
                        .HasColumnType("TEXT");

                    b.Property<int>("poll_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("option_id");

                    b.ToTable("Options");
                });

            modelBuilder.Entity("PoolApi.Pool", b =>
                {
                    b.Property<int>("poll_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("poll_description")
                        .HasColumnType("TEXT");

                    b.HasKey("poll_id");

                    b.ToTable("Values");
                });

            modelBuilder.Entity("PoolApi.View", b =>
                {
                    b.Property<int>("poll_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("date")
                        .HasColumnType("TEXT");

                    b.HasKey("poll_id");

                    b.ToTable("Views");
                });

            modelBuilder.Entity("PoolApi.Vote", b =>
                {
                    b.Property<int>("option_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("date")
                        .HasColumnType("TEXT");

                    b.HasKey("option_id");

                    b.ToTable("Votes");
                });
#pragma warning restore 612, 618
        }
    }
}
